-- Цей SQL-запит поверне проект з найбільшою кількістю місяців
SELECT *
FROM project
WHERE EXTRACT(MONTH FROM END_DATE) - EXTRACT(MONTH FROM START_DATE) +
      12 * (EXTRACT(YEAR FROM END_DATE) - EXTRACT(YEAR FROM START_DATE)) = (
    SELECT MAX(EXTRACT(MONTH FROM END_DATE) - EXTRACT(MONTH FROM START_DATE) +
               12 * (EXTRACT(YEAR FROM END_DATE) - EXTRACT(YEAR FROM START_DATE)))
    FROM project
);